### ISSUE TITLE
openttd failed to build on 10.12

### ISSUE THREAD

**Issue by Gr1N** [Homebrew/homebrew-games#711]
openttd failed to build on 10.12
https://gist.github.com/anonymous/033bb352d658ae9ccd1ed3032b014f9e

```
[SRC] Compiling video/cocoa/event.mm
[SRC] Compiling video/cocoa/fullscreen.mm
[SRC] Compiling video/cocoa/wnd_quartz.mm
[SRC] Compiling video/cocoa/wnd_quickdraw.mm
[SRC] Linking openttd
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      convert_tofrom_fs(void*, char const*) in unix.o
  "_iconv_open", referenced from:
      OTTD2FS(char const*) in unix.o
      FS2OTTD(char const*) in unix.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [openttd] Error 1
make: *** [all] Error 1
```

**Comment by tomyun** [comment]
Seems like CLT is required to build without errors. You may install CLT by running `xcode-select --install` or wait a bit until we upload a new bottle for Sierra.

**Comment by tomyun** [comment]
`openttd` bottles are updated with f326d9fde3a7ec7e348a1cbeb60bf78c554d9218. Please try installing it by `brew install openttd`.

**Comment by Gr1N** [comment]
@tomyun works now for me, thanks

**Comment by tony** [comment]
@tomyun is there a way to know the libs/configure options you're using when creating the bottles?  Trying to get openttd to build from source outside of brew.

related https://github.com/Homebrew/homebrew-games/issues/464#issuecomment-236414302

**Comment by tomyun** [comment]
@tony bottling is automatically done by CI server, but should not differ much from building on your own machine. `brew install -d -v openttd` may give you an idea how it actually builds. Also note that we apply [some patches](https://github.com/Homebrew/homebrew-games/blob/master/openttd.rb) for compatibility issues on newer macOS ([FS#6295](https://bugs.openttd.org/task/6295), [FS#6380](https://bugs.openttd.org/task/6380)).

**Comment by tony** [comment]
```
Changing install name in /usr/local/Cellar/openttd/1.6.1/OpenTTD.app/Contents/MacOS/openttd
  from @@HOMEBREW_PREFIX@@/opt/xz/lib/liblzma.5.dylib
    to /usr/local/opt/xz/lib/liblzma.5.dylib
Changing install name in /usr/local/Cellar/openttd/1.6.1/OpenTTD.app/Contents/MacOS/openttd
  from @@HOMEBREW_PREFIX@@/opt/lzo/lib/liblzo2.2.dylib
    to /usr/local/opt/lzo/lib/liblzo2.2.dylib
```

I think that could be it.  Some of the ways I build tend to give me linking issues with lzma/lzo.  Interested in seeing how to get the exact behavior (``./configure``, the CI server settings, etc.) Even if it was to document it for others. 

Building MacOS apps from source is just tricky business a lot of the time.

**Comment by tomyun** [comment]
@tony You could also manually run `./configure` in an interactive session by running `brew install -d -v -i openttd`. I don't know much about the CI server settings as I don't have an access to it either, but it shouldn't really matter because you can build bottles on your local machine too. `brew bottle` option might be of your interest although I have little experience with it. If you have further questions, feel free to open a new issue. Thanks!
