### ISSUE TITLE
openttd fails to build on 10.11.2

### ISSUE THREAD

**Issue by linnik** [Homebrew/homebrew-games#464]
```
==> ./configure --prefix-dir=/usr/local/Cellar/openttd/1.5.1
==> make bundle
Last 15 lines from /Users/slava/Library/Logs/Homebrew/openttd/02.make:
[SRC] Compiling music/cocoa_m.cpp
[SRC] Compiling music/extmidi.cpp
[SRC] Compiling music/null_m.cpp
[SRC] Compiling music/qtmidi.cpp
[SRC] Compiling music_gui.cpp
/private/tmp/openttd20151219-1731-lbal8q/openttd-1.5.1/src/music/cocoa_m.cpp:76:4: error: no matching function for call to 'AUGraphNodeInfo'
                        AUGraphNodeInfo(graph, node, &desc, &unit);
                        ^~~~~~~~~~~~~~~
/System/Library/Frameworks/AudioToolbox.framework/Headers/AUGraph.h:179:1: note: candidate function not viable: no known conversion from 'ComponentDescription *' to 'AudioComponentDescription * _Nullable' (aka 'AudioComponentDescription *') for 3rd argument
AUGraphNodeInfo(        AUGraph                                                                 inGraph,
^
1 error generated.
make[1]: *** [music/cocoa_m.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 1
```
```
➜  ~  brew doctor
Your system is ready to brew.
```

**Comment by kryachkov** [comment]
same issue

**Comment by mistydemeo** [comment]
Please read the [troubleshooting guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting), follow the steps there, and post the output of `brew gist-logs openttd`. Thanks!

**Comment by mistydemeo** [comment]
Ping

**Comment by linnik** [comment]
latest version of openttd 1.5.3_1 works well for me now (but this time installation were using binary (?) files, without building from source)

**Comment by tony** [comment]
whoever compiled it has 10.8SDK installed.  If you're on OS X El Capitan and want to build OpenTTD from source in anyway (as of July 31, 2016), you need to use 10.8 SDK. 

go to https://developer.apple.com, sign in, download Xcode 5.1.1 DMG, mount it

copy the SDK: ``sudo cp -a /Volumes/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs``

when building, include the 10.8 SDK path in ``CFLAGS``:

```./configure --enable-static --without-liblzo2 --without-osx-sysroot CFLAGS="-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk" LDFLAGS="-stdlib=libstdc++"```

You may be able to omit ``-enable-static``, ``-without-liblzo2``, etc. In addition you may be able to get away without ``stdlib=libstdc++`` since i think thats on by default now

```make```

to test locally ```./bin/openttd```

enjoy

**Comment by shatteringlass** [comment]
I think we need a better solution now that 10.12 is out and OpenTTD still won't build using XCode8.

**Comment by tomyun** [comment]
@shatteringlass `brew install openttd` builds from source without any issue on my 10.12 machine. It has the latest Xcode 8.0 installed. If you still have a problem, please open a new issue following the steps in the [troubleshooting guide](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md). Thanks!
